### ISSUE TITLE
ProviderNotFoundException

### ISSUE THREAD

**Issue by MuhammadSafyanTariq** [RivaanRanawat/instagram-flutter-clone#15]
![issue3](https://user-images.githubusercontent.com/117639744/200288297-61ee5d70-71a6-4877-9ddf-9938b0b351d2.PNG)
 
I am facing this issue...

This is my code give below

![issue2](https://user-images.githubusercontent.com/117639744/200288426-2c57d6d6-a71f-4f95-9e3e-a5f08b8e6eee.PNG)
![issue1](https://user-images.githubusercontent.com/117639744/200288447-08901706-4610-4662-a040-8d3c00dca8a0.PNG)

**Comment by RivaanRanawat** [comment]
Has this issue been resolved?

**Comment by RivaanRanawat** [comment]
No reply so closing the issue. Feel free to reopen
