### ISSUE TITLE
Search Screen StateError (Bad state: field does not exist within the DocumentSnapshotPlatform)

### ISSUE THREAD

**Issue by Davepn16** [RivaanRanawat/instagram-flutter-clone#18]
If you get "StateError (Bad state: field does not exist within the DocumentSnapshotPlatform)" on search screen at : 
```
(snapshot.data! as dynamic).docs[index] ['photoUrl'],
```

you should use:
`if (snapshot.connectionState == ConnectionState.waiting)`

instead of :
`if (!snapshot.hasData)`

It looks like hasdata returns true for any non-null data, and [] is non-null data, hence hasdata will return true while the snapshot is still in a waiting state.

Always use ConnectionState.waiting, never use junky hasdata which actually means "not null".

**Comment by RivaanRanawat** [comment]
Thanks for the tip!

**Comment by muhammetaydinn** [comment]
![image](https://user-images.githubusercontent.com/72871376/221392924-f07e47e6-b8f7-4473-97d0-343dae4be34f.png)
not solved
open issue please @RivaanRanawat

**Comment by muhammetaydinn** [comment]
I think we have to check the photoUrl null or not before.
solved but not sure 
```dart
  backgroundImage: NetworkImage(
                                (snapshot.data! as dynamic)
                                        .docs[index]
                                        .data()["photoUrl"] ??
                                    imageUrl),
                          ),
                          ```

**Comment by LosPhilly** [comment]
> 

This worked for me thanks for the tip!

**Comment by LosPhilly** [comment]
> If you get "StateError (Bad state: field does not exist within the DocumentSnapshotPlatform)" on search screen at :
> 
> ```
> (snapshot.data! as dynamic).docs[index] ['photoUrl'],
> ```
> 
> you should use: `if (snapshot.connectionState == ConnectionState.waiting)`
> 
> instead of : `if (!snapshot.hasData)`
> 
> It looks like hasdata returns true for any non-null data, and [] is non-null data, hence hasdata will return true while the snapshot is still in a waiting state.
> 
> Always use ConnectionState.waiting, never use junky hasdata which actually means "not null".

Thanks for the tip this added to the success!
