### ISSUE TITLE
flutter.compileSdkVersion question

### ISSUE THREAD

**Issue by dyardy** [RivaanRanawat/instagram-flutter-clone#2]
In the android/app/build.gradle you refernced flutter.compileSdkVersion (this appears to be read from somewhere else?, how/where is the compileSdkVersion set?)

Likewise you referenced flutter.targetSdkVersion (where does this come from?)

**Comment by dyardy** [comment]
new approach with 2.8 flutter

**Comment by ugyen-chophel** [comment]
It is referenced from flutter.gradle file from 
_$FLUTTER_ROOT/packages/flutter_tools/gradle/flutter.gradle_

$FLUTTER_ROOT = Root directory of Flutter SDK
[
![flutter gradle](https://user-images.githubusercontent.com/60716094/151697618-dc518e9a-42df-46fd-a2be-cce3caa71258.png)
](url)
