### ISSUE TITLE
class AuthMetods methods conditions 

### ISSUE THREAD

**Issue by bedfir** [RivaanRanawat/instagram-flutter-clone#9]
I think you have made a mistake on both methods **loginUser** and **signUpUser** you have used operator **OR** instead of **AND**.
therefore the fields are not required.

`
if (email.isNotEmpty || password.isNotEmpty || username.isNotEmpty || bio.isNotEmpty || file != null) {
      
    return "Only one fiield are required with the || operator";
}
`

**Comment by jinosh05** [comment]
Check my Fork for fixing the issue
